version: '3.7'

services:
    emenu:
        container_name: emenu
        image: emenu:latest
        build:
            context: ./
            dockerfile: .Dockerfile
        env_file:
            - .env
        expose:
            - 5001
        command: >
           bash -c "python manage.py collectstatic --no-input &&
                    python manage.py migrate &&
                    gunicorn service.wsgi:application  --name emenu --workers 2 --bind=0.0.0.0:5001 --capture-output --access-logfile - -t 300"
        volumes:
            - ./static:/static

    nginx_emenu:
        container_name: nginx_emenu
        build: ./nginx
        ports:
            - 5001:80
        volumes:
            - ./static:/static
        depends_on:
            - emenu

volumes:
    postgres_data:
    static: {}
