version: '3.7'

services:
    emenu:
        container_name: emenu
        image: emenu:latest
        build:
            context: ./
            dockerfile: .Dockerfile
        env_file:
            - .env
        expose:
            - 5001
        command: >
           bash -c "python manage.py collectstatic --no-input &&
                    python manage.py migrate &&
                    gunicorn service.wsgi:application  --name emenu --workers 2 --bind=0.0.0.0:5001 --capture-output --access-logfile - -t 300"
        volumes:
            - ./static:/static

volumes:
    postgres_data:
    static: {}
