version: '3.7'

services:
    postgresql:
        container_name: postgresql
        image: postgres:latest
        restart: on-failure
        ports:
            - "5431:5431"
        env_file:
            - .env
        environment:
            - PG_TRUST_LOCALNET=true
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    emenu:
        container_name: emenu
        image: emenu:latest
        build:
            context: ./
            dockerfile: .Dockerfile
        env_file:
            - .env
        ports:
            - "5001:5001"
        command: >
            bash -c "python manage.py collectstatic --no-input &&
                    python manage.py migrate &&
                    gunicorn service.wsgi:application  --name emenu --workers 2 --bind=0.0.0.0:5001 --capture-output --access-logfile - -t 300"
        labels:
            deck-chores.mailing.command: sh -c "python manage.py email_for_subscribers"
            deck-chores.mailing.cron: "0 */10 * * *"
        volumes:
            - ./static:/static

    deck-chores:
        container_name: deck-chores
        image: funkyfuture/deck-chores:1
        restart: unless-stopped
        environment:
            TIMEZONE: Europe/Warsaw
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    static: {}
    postgres-data: {}
