name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy na Produkcję
    runs-on: ubuntu-latest
    steps:
    - name: Deploy app to DigitalOcean
      if: always()
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.DIGITALOCEAN_HOST}}
        key: ${{secrets.DIGITALOCEAN_KEY}}
        username: ${{secrets.DIGITALOCEAN_USER}}
        script: |
          cd /root/apps
          cd emenu
          git checkout .
          git fetch
          git checkout master
          git pull origin master
          make stop
          make start-build
          echo 'Application Updated Successfull'


